name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          docker system prune --all --force
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: LilLisa_Server/build/dockerfile_prod
          context: LilLisa_Server
          tags: radiantone/rocknbot-server:staging
          provenance: true
          sbom: true
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: lil-lisa-web/build/Dockerfile_prod
          context: lil-lisa-web
          tags: radiantone/rocknbot-web:staging
          provenance: true
          sbom: true
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: lil-lisa/build/dockerfile_prod
          context: lil-lisa
          tags: radiantone/rocknbot-slack:staging
          provenance: true
          sbom: true
